set_property SRC_FILE_INFO {cfile:{/home/fpga/FPGA/Vivado/octal decoder/octal decoder.srcs/constrs_1/new/octal_constraints.xdc} rfile:{../../../octal decoder.srcs/constrs_1/new/octal_constraints.xdc} id:1} [current_design]
set_property src_info {type:XDC file:1 line:6 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN Y11 IOSTANDARD LVCMOS33 } [get_ports {D}]
set_property src_info {type:XDC file:1 line:8 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN AA11 IOSTANDARD LVCMOS33 } [get_ports {A}]
set_property src_info {type:XDC file:1 line:10 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {   PACKAGE_PIN Y10 IOSTANDARD LVCMOS33 } [get_ports {Dp}]
set_property src_info {type:XDC file:1 line:12 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {   PACKAGE_PIN AA9 IOSTANDARD LVCMOS33 } [get_ports {E}]
set_property src_info {type:XDC file:1 line:14 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {   PACKAGE_PIN W12 IOSTANDARD LVCMOS33 } [get_ports {B}]
set_property src_info {type:XDC file:1 line:16 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {   PACKAGE_PIN W11 IOSTANDARD LVCMOS33 } [get_ports {C}]
set_property src_info {type:XDC file:1 line:18 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {  PACKAGE_PIN V10 IOSTANDARD LVCMOS33 } [get_ports {G}]
set_property src_info {type:XDC file:1 line:20 export:INPUT save:INPUT read:READ} [current_design]
set_property  -dict {   PACKAGE_PIN W8 IOSTANDARD LVCMOS33 } [get_ports {F}]
set_property src_info {type:XDC file:1 line:25 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN H18 IOSTANDARD LVCMOS25} [get_ports Din0]
set_property src_info {type:XDC file:1 line:27 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN H17 IOSTANDARD LVCMOS25 } [get_ports Din1]
set_property src_info {type:XDC file:1 line:29 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN M15 IOSTANDARD LVCMOS25 } [get_ports Din2]
