# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
set_msg_config  -ruleid {1}  -id {Project 1-311}  -string {{CRITICAL WARNING: [Project 1-311] Could not find the file '/home/trk/git_fpga/new_git/Downloads/Debounce.vhd', nor could it be found using path '/home/trk/Downloads/Debounce.vhd'.}}  -suppress 
set_msg_config  -ruleid {2}  -id {Vivado 12-106}  -string {{ERROR: [Vivado 12-106] *** Exception: java.lang.NullPointerException: Failed to retrieve atom name. (See /home/fpga/vivado_pid31376.debug)}}  -suppress 
set_msg_config  -ruleid {3}  -id {filemgmt 20-728}  -string {{CRITICAL WARNING: [filemgmt 20-728] File analysis is incomplete due to previous errors / warnings. Previous successful analysis data will be used for elaboration. [/home/trk/git_fpga/new_git/projects/Vivado/verilog/Lab5/Lab5.1.srcs/sim_1/new/Counter_tb.v:1]}}  -suppress 
create_project -in_memory -part xc7z020clg484-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir /home/trk/git_fpga/new_git/projects/Vivado/verilog/Lab5/Lab5.1.cache/wt [current_project]
set_property parent.project_path /home/trk/git_fpga/new_git/projects/Vivado/verilog/Lab5/Lab5.1.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part em.avnet.com:zed:part0:1.3 [current_project]
set_property ip_output_repo /home/trk/git_fpga/new_git/projects/Vivado/verilog/Lab5/Lab5.1.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {
  /home/trk/git_fpga/projects/Vivado/verilog/Lab4/One_shot.v
  /home/trk/git_fpga/new_git/projects/Vivado/verilog/Lab5/Lab5.1.srcs/sources_1/new/Counter.v
  /home/trk/git_fpga/projects/Vivado/verilog/Lab4/top.v
  /home/trk/git_fpga/new_git/projects/Vivado/verilog/Lab5/Lab5.1.srcs/sources_1/new/Moore.v
}
read_vhdl -library xil_defaultlib /home/trk/Downloads/Debounce.vhd
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc /home/trk/git_fpga/new_git/projects/Vivado/verilog/Lab5/Lab5.1.srcs/constrs_1/new/L5_constraints.xdc
set_property used_in_implementation false [get_files /home/trk/git_fpga/new_git/projects/Vivado/verilog/Lab5/Lab5.1.srcs/constrs_1/new/L5_constraints.xdc]


synth_design -top top -part xc7z020clg484-1


write_checkpoint -force -noxdef top.dcp

catch { report_utilization -file top_utilization_synth.rpt -pb top_utilization_synth.pb }
