# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir /home/fpga/FPGA/Vivado/MEMORY/MEMORY.cache/wt [current_project]
set_property parent.project_path /home/fpga/FPGA/Vivado/MEMORY/MEMORY.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
read_vhdl -library xil_defaultlib /home/fpga/FPGA/Vivado/MEMORY/MEMORY.srcs/sources_1/new/RAM.vhd
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc /home/fpga/FPGA/Vivado/MEMORY/MEMORY.srcs/constrs_1/new/ram_constraints.xdc
set_property used_in_implementation false [get_files /home/fpga/FPGA/Vivado/MEMORY/MEMORY.srcs/constrs_1/new/ram_constraints.xdc]


synth_design -top RAM -part xc7a100tcsg324-1


write_checkpoint -force -noxdef RAM.dcp

catch { report_utilization -file RAM_utilization_synth.rpt -pb RAM_utilization_synth.pb }
