set_property SRC_FILE_INFO {cfile:/home/fpga/FPGA/Vivado/seven_seg_rtc/seven_seg_rtc.srcs/constrs_1/new/seven_seg_rtc.xdc rfile:../../../seven_seg_rtc.srcs/constrs_1/new/seven_seg_rtc.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:6 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN Y11  } [get_ports { D }]
set_property src_info {type:XDC file:1 line:9 export:INPUT save:INPUT read:READ} [current_design]
set_property  -dict { PACKAGE_PIN AA11 IOSTANDARD LVCMOS33 } [get_ports {A}]
set_property src_info {type:XDC file:1 line:12 export:INPUT save:INPUT read:READ} [current_design]
set_property  -dict {   PACKAGE_PIN Y10 IOSTANDARD LVCMOS33 } [get_ports { Dp }]
set_property src_info {type:XDC file:1 line:15 export:INPUT save:INPUT read:READ} [current_design]
set_property  -dict {   PACKAGE_PIN AA9 IOSTANDARD LVCMOS33 } [get_ports { E }]
set_property src_info {type:XDC file:1 line:18 export:INPUT save:INPUT read:READ} [current_design]
set_property  -dict {   PACKAGE_PIN W11 IOSTANDARD LVCMOS33 } [get_ports { C }]
set_property src_info {type:XDC file:1 line:21 export:INPUT save:INPUT read:READ} [current_design]
set_property  -dict {  PACKAGE_PIN V10 IOSTANDARD LVCMOS33 } [get_ports { G }]
set_property src_info {type:XDC file:1 line:23 export:INPUT save:INPUT read:READ} [current_design]
set_property  -dict {  PACKAGE_PIN W12 IOSTANDARD LVCMOS33 } [get_ports { B }]
set_property src_info {type:XDC file:1 line:27 export:INPUT save:INPUT read:READ} [current_design]
set_property  -dict {   PACKAGE_PIN W8 IOSTANDARD LVCMOS33 } [get_ports { F }]
set_property src_info {type:XDC file:1 line:29 export:INPUT save:INPUT read:READ} [current_design]
set_property  -dict { PACKAGE_PIN Y9 IOSTANDARD LVCMOS33 } [get_ports { clk }]
set_property src_info {type:XDC file:1 line:31 export:INPUT save:INPUT read:READ} [current_design]
set_property  -dict { PACKAGE_PIN T18 IOSTANDARD LVCMOS33 } [get_ports { rst }]
