# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7z020clg484-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir /home/fpga/FPGA/Vivado/seven_seg_rtc/seven_seg_rtc.cache/wt [current_project]
set_property parent.project_path /home/fpga/FPGA/Vivado/seven_seg_rtc/seven_seg_rtc.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part em.avnet.com:zed:part0:1.3 [current_project]
read_verilog -library xil_defaultlib /home/fpga/FPGA/Vivado/seven_seg_rtc/seven_seg_rtc.v
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc /home/fpga/FPGA/Vivado/seven_seg_rtc/seven_seg_rtc.srcs/constrs_1/new/seven_seg_rtc.xdc
set_property used_in_implementation false [get_files /home/fpga/FPGA/Vivado/seven_seg_rtc/seven_seg_rtc.srcs/constrs_1/new/seven_seg_rtc.xdc]


synth_design -top seven_seg_rtc -part xc7z020clg484-1


write_checkpoint -force -noxdef seven_seg_rtc.dcp

catch { report_utilization -file seven_seg_rtc_utilization_synth.rpt -pb seven_seg_rtc_utilization_synth.pb }
